<?php get_header(); ?>

<section class="arena" id="home">
    <h1>Welcome to Esports Arena</h1>
    <p>Your ultimate destination for gaming news, leaderboards, and live tournaments.</p>
</section>

<?php quote_of_the_day(); ?>

<!-- Leaderboard Section with Bootstrap Cards - all description and team names are fake and generated by AI, therefore cannot be trusted, it is just a sample -->

<div id="game-leaderboard" class="container mt-5 leaderboard-section">
    <h2>Top Teams</h2>

    <!-- Accordion for Game Categories -->
    <div id="leaderboardAccordion">
        
        <!-- League of Legends -->

        <div class="game-leaderboard">
            <div class="card">
                <div class="card-header" id="headingLoL">
                    <h5 class="mb-0">
                        <button class="btn btn-link" data-toggle="collapse" data-target="#lolLeaderboard" aria-expanded="true" aria-controls="lolLeaderboard">
                            League of Legends
                        </button>
                    </h5>
                </div>

                <div id="lolLeaderboard" class="collapse" aria-labelledby="headingLoL" data-parent="#leaderboardAccordion">
                    <div class="card-body">

                        <!-- Nested Accordion for Teams -->
                        <div class="accordion" id="lolAccordion">
                            <!-- Team 1 -->
                            <div class="list-group-item">
                                <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#lol-team-1" aria-expanded="false" aria-controls="lol-team-1">
                                    Team Alpha - 500 Points
                                </button>
                                <div id="lol-team-1" class="collapse" data-parent="#lolAccordion">
                                    <p>Team Alpha is a top-performing team in the League of Legends scene!</p>
                                </div>
                            </div>
                            <!-- Team 2 -->
                            <div class="list-group-item">
                                <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#lol-team-2" aria-expanded="false" aria-controls="lol-team-2">
                                    Team Beta - 450 Points
                                </button>
                                <div id="lol-team-2" class="collapse" data-parent="#lolAccordion">
                                    <p>Team Beta is known for their aggressive gameplay!</p>
                                </div>
                            </div>
                            <!-- Team 3 -->
                            <div class="list-group-item">
                                <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#lol-team-3" aria-expanded="false" aria-controls="lol-team-3">
                                    Team Gamma - 430 Points
                                </button>
                                <div id="lol-team-3" class="collapse" data-parent="#lolAccordion">
                                    <p>Team Gamma focuses on strategic map control!</p>
                                </div>
                            </div>
                            <!-- Team 4 -->
                            <div class="list-group-item">
                                <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#lol-team-4" aria-expanded="false" aria-controls="lol-team-4">
                                    Team Delta - 400 Points
                                </button>
                                <div id="lol-team-4" class="collapse" data-parent="#lolAccordion">
                                    <p>Team Delta is famous for their coordination in team fights!</p>
                                </div>
                            </div>
                            <!-- Team 5 -->
                            <div class="list-group-item">
                                <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#lol-team-5" aria-expanded="false" aria-controls="lol-team-5">
                                    Team Epsilon - 380 Points
                                </button>
                                <div id="lol-team-5" class="collapse" data-parent="#lolAccordion">
                                    <p>Team Epsilon is known for their quick rotations and objective control!</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Valorant -->

        <div class="game-leaderboard mt-4">
            <div class="card">
                <div class="card-header" id="headingValorant">
                    <h5 class="mb-0">
                        <button class="btn btn-link" data-toggle="collapse" data-target="#valorantLeaderboard" aria-expanded="false" aria-controls="valorantLeaderboard">
                            Valorant
                        </button>
                    </h5>
                </div>

                <div id="valorantLeaderboard" class="collapse" aria-labelledby="headingValorant" data-parent="#leaderboardAccordion">
                    <div class="card-body">

                        <!-- Nested Accordion for Teams -->
                        <div class="accordion" id="valorantAccordion">

                            <!-- Team 1 -->
                            <div class="list-group-item">
                                <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#valorant-team-1" aria-expanded="false" aria-controls="valorant-team-1">
                                    Team Omega - 400 Points
                                </button>
                                <div id="valorant-team-1" class="collapse" data-parent="#valorantAccordion">
                                    <p>Team Omega is known for its aggressive plays and fast rotations!</p>
                                </div>
                            </div>

                            <!-- Team 2 -->
                            <div class="list-group-item">
                                <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#valorant-team-2" aria-expanded="false" aria-controls="valorant-team-2">
                                    Team Sigma - 380 Points
                                </button>
                                <div id="valorant-team-2" class="collapse" data-parent="#valorantAccordion">
                                    <p>Team Sigma excels in strategic play and perfect timing!</p>
                                </div>
                            </div>

                            <!-- Team 3 -->
                            <div class="list-group-item">
                                <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#valorant-team-3" aria-expanded="false" aria-controls="valorant-team-3">
                                    Team Zeta - 360 Points
                                </button>
                                <div id="valorant-team-3" class="collapse" data-parent="#valorantAccordion">
                                    <p>Team Zeta is known for their sharp aim and quick decision-making!</p>
                                </div>
                            </div>

                            <!-- Team 4 -->
                            <div class="list-group-item">
                                <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#valorant-team-4" aria-expanded="false" aria-controls="valorant-team-4">
                                    Team Theta - 350 Points
                                </button>
                                <div id="valorant-team-4" class="collapse" data-parent="#valorantAccordion">
                                    <p>Team Theta is a versatile team capable of adapting to any situation!</p>
                                </div>
                            </div>

                            <!-- Team 5 -->
                            <div class="list-group-item">
                                <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#valorant-team-5" aria-expanded="false" aria-controls="valorant-team-5">
                                    Team Iota - 340 Points
                                </button>
                                <div id="valorant-team-5" class="collapse" data-parent="#valorantAccordion">
                                    <p>Team Iota specializes in eco-rounds and smart plays!</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Rocket League -->

        <div class="game-leaderboard mt-4">
            <div class="card">
                <div class="card-header" id="headingRocketLeague">
                    <h5 class="mb-0">
                        <button class="btn btn-link" data-toggle="collapse" data-target="#rocketLeagueLeaderboard" aria-expanded="false" aria-controls="rocketLeagueLeaderboard">
                            Rocket League
                        </button>
                    </h5>
                </div>

                <div id="rocketLeagueLeaderboard" class="collapse" aria-labelledby="headingRocketLeague" data-parent="#leaderboardAccordion">
                    <div class="card-body">

                        <!-- Nested Accordion for Teams -->
                        <div class="accordion" id="rocketLeagueAccordion">

                            <!-- Team 1 -->
                            <div class="list-group-item">
                                <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#rocket-league-team-1" aria-expanded="false" aria-controls="rocket-league-team-1">
                                    Team Phoenix - 450 Points
                                </button>
                                <div id="rocket-league-team-1" class="collapse" data-parent="#rocketLeagueAccordion">
                                    <p>Team Phoenix is known for their speed and precision on the field!</p>
                                </div>
                            </div>

                            <!-- Team 2 -->
                            <div class="list-group-item">
                                <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#rocket-league-team-2" aria-expanded="false" aria-controls="rocket-league-team-2">
                                    Team Inferno - 430 Points
                                </button>
                                <div id="rocket-league-team-2" class="collapse" data-parent="#rocketLeagueAccordion">
                                    <p>Team Inferno specializes in aerial plays and fast breaks!</p>
                                </div>
                            </div>

                            <!-- Team 3 -->
                            <div class="list-group-item">
                                <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#rocket-league-team-3" aria-expanded="false" aria-controls="rocket-league-team-3">
                                    Team Blizzard - 410 Points
                                </button>
                                <div id="rocket-league-team-3" class="collapse" data-parent="#rocketLeagueAccordion">
                                    <p>Team Blizzard is known for their strong defensive setups!</p>
                                </div>
                            </div>

                            <!-- Team 4 -->
                            <div class="list-group-item">
                                <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#rocket-league-team-4" aria-expanded="false" aria-controls="rocket-league-team-4">
                                    Team Avalanche - 400 Points
                                </button>
                                <div id="rocket-league-team-4" class="collapse" data-parent="#rocketLeagueAccordion">
                                    <p>Team Avalanche is recognized for their coordination and team plays!</p>
                                </div>
                            </div>

                            <!-- Team 5 -->
                            <div class="list-group-item">
                                <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#rocket-league-team-5" aria-expanded="false" aria-controls="rocket-league-team-5">
                                    Team Thunder - 410 Points
                                </button>
                                <div id="rocket-league-team-5" class="collapse" data-parent="#rocketLeagueAccordion">
                                    <p>Team Thunder focuses on quick counter-attacks and fast rotations!</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Fortnite -->
        
        <div class="game-leaderboard mt-4">
            <div class="card">
                <div class="card-header" id="headingFortnite">
                    <h5 class="mb-0">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#fortniteLeaderboard" aria-expanded="false" aria-controls="fortniteLeaderboard">
                                Fortnite
                            </button>
                        </h5>
                    </div>

                    <div id="fortniteLeaderboard" class="collapse" aria-labelledby="headingFortnite" data-parent="#leaderboardAccordion">
                        <div class="card-body">

                            <!-- Nested Accordion for Teams -->
                            <div class="accordion" id="fortniteAccordion">

                                <!-- Team 1 -->
                                <div class="list-group-item">
                                    <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#fortnite-team-1" aria-expanded="false" aria-controls="fortnite-team-1">
                                        Team Victory - 650 Points
                                    </button>
                                    <div id="fortnite-team-1" class="collapse" data-parent="#fortniteAccordion">
                                        <p>Team Victory dominates the battlefield with precise shooting!</p>
                                    </div>
                                </div>

                                <!-- Team 2 -->
                                <div class="list-group-item">
                                <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#fortnite-team-2" aria-expanded="false" aria-controls="fortnite-team-2">
                                        Team Storm - 620 Points
                                    </button>
                                    <div id="fortnite-team-2" class="collapse" data-parent="#fortniteAccordion">
                                        <p>Team Storm excels at building and rapid-fire tactics!</p>
                                    </div>
                                </div>

                                <!-- Team 3 -->
                                <div class="list-group-item">
                                <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#fortnite-team-3" aria-expanded="false" aria-controls="fortnite-team-3">
                                        Team Blitz - 600 Points
                                    </button>
                                    <div id="fortnite-team-3" class="collapse" data-parent="#fortniteAccordion">
                                        <p>Team Blitz is known for fast eliminations and aggressive plays!</p>
                                    </div>
                                </div>

                                <!-- Team 4 -->
                                <div class="list-group-item">
                                <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#fortnite-team-4" aria-expanded="false" aria-controls="fortnite-team-4">
                                        Team Galaxy - 580 Points
                                    </button>
                                    <div id="fortnite-team-4" class="collapse" data-parent="#fortniteAccordion">
                                        <p>Team Galaxy has a unique strategy of surprise attacks from the high ground!</p>
                                    </div>
                                </div>

                                <!-- Team 5 -->
                                <div class="list-group-item">
                                <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#fortnite-team-5" aria-expanded="false" aria-controls="fortnite-team-5">
                                        Team Thunder - 550 Points
                                    </button>
                                    <div id="fortnite-team-5" class="collapse" data-parent="#fortniteAccordion">
                                        <p>Team Thunder thrives with perfect timing and tactical retreats!</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Dead by Daylight (DBD) -->

            <div class="game-leaderboard mt-4">
                <div class="card">
                    <div class="card-header" id="headingDBD">
                        <h5 class="mb-0">
                            <button class="btn btn-link" data-toggle="collapse" data-target="#dbdLeaderboard" aria-expanded="false" aria-controls="dbdLeaderboard">
                                Dead by Daylight
                            </button>
                        </h5>
                    </div>

                    <div id="dbdLeaderboard" class="collapse" aria-labelledby="headingDBD" data-parent="#leaderboardAccordion">
                        <div class="card-body">

                            <!-- Nested Accordion for Teams -->
                            <div class="accordion" id="dbdAccordion">

                                <!-- Team 1 -->
                                <div class="list-group-item">
                                    <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#dbd-team-1" aria-expanded="false" aria-controls="dbd-team-1">
                                        Team Shivers - 700 Points
                                    </button>
                                    <div id="dbd-team-1" class="collapse" data-parent="#dbdAccordion">
                                        <p>Team Shivers is known for their stealthy killer plays!</p>
                                    </div>
                                </div>

                                <!-- Team 2 -->
                                <div class="list-group-item">
                                    <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#dbd-team-2" aria-expanded="false" aria-controls="dbd-team-2">
                                        Team Nightmares - 680 Points
                                    </button>
                                    <div id="dbd-team-2" class="collapse" data-parent="#dbdAccordion">
                                        <p>Team Nightmares specializes in strategic traps and ambushes!</p>
                                    </div>
                                </div>

                                <!-- Team 3 -->
                                <div class="list-group-item">
                                    <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#dbd-team-3" aria-expanded="false" aria-controls="dbd-team-3">
                                        Team Echo - 660 Points
                                    </button>
                                    <div id="dbd-team-3" class="collapse" data-parent="#dbdAccordion">
                                        <p>Team Echo utilizes efficient teamwork to outsmart survivors!</p>
                                    </div>
                                </div>

                                <!-- Team 4 -->
                                <div class="list-group-item">
                                    <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#dbd-team-4" aria-expanded="false" aria-controls="dbd-team-4">
                                        Team Wraith - 640 Points
                                    </button>
                                    <div id="dbd-team-4" class="collapse" data-parent="#dbdAccordion">
                                        <p>Team Wraith is skilled at evading detection and striking fast!</p>
                                    </div>
                                </div>

                                <!-- Team 5 -->
                                <div class="list-group-item">
                                    <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#dbd-team-5" aria-expanded="false" aria-controls="dbd-team-5">
                                        Team Terror - 620 Points
                                    </button>
                                    <div id="dbd-team-5" class="collapse" data-parent="#dbdAccordion">
                                        <p>Team Terror strikes fear into survivors with unexpected attacks!</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Dota 2 -->

            <div class="game-leaderboard mt-4">
                <div class="card">
                    <div class="card-header" id="headingDota2">
                        <h5 class="mb-0">
                            <button class="btn btn-link" data-toggle="collapse" data-target="#dota2Leaderboard" aria-expanded="false" aria-controls="dota2Leaderboard">
                                Dota 2
                            </button>
                        </h5>
                    </div>

                    <div id="dota2Leaderboard" class="collapse" aria-labelledby="headingDota2" data-parent="#leaderboardAccordion">
                        <div class="card-body">

                            <!-- Nested Accordion for Teams -->
                            <div class="accordion" id="dota2Accordion">
                            
                                <!-- Team 1 -->
                                <div class="list-group-item">
                                    <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#dota2-team-1" aria-expanded="false" aria-controls="dota2-team-1">
                                        Team Immortals - 750 Points
                                    </button>
                                    <div id="dota2-team-1" class="collapse" data-parent="#dota2Accordion">                                  
                                        <p>Team Immortals is famous for their flawless coordination and ultimate strategies!</p>
                                    </div>
                                </div>

                                <!-- Team 2 -->
                                <div class="list-group-item">
                                    <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#dota2-team-2" aria-expanded="false" aria-controls="dota2-team-2">
                                        Team Dynasty - 730 Points
                                    </button>
                                    <div id="dota2-team-2" class="collapse" data-parent="#dota2Accordion">  
                                        <p>Team Dynasty excels in lane control and smart rotations!</p>
                                    </div>
                                </div>

                                <!-- Team 3 -->
                                <div class="list-group-item">
                                    <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#dota2-team-3" aria-expanded="false" aria-controls="dota2-team-3">
                                        Team Titans - 710 Points
                                    </button>
                                    <div id="dota2-team-3" class="collapse" data-parent="#dota2Accordion">  
                                        <p>Team Titans is known for aggressive ganks and outsmarting their opponents!</p>
                                    </div>
                                </div>

                                <!-- Team 4 -->
                                <div class="list-group-item">
                                    <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#dota2-team-4" aria-expanded="false" aria-controls="dota2-team-4">
                                        Team Thunder - 690 Points
                                    </button>
                                    <div id="dota2-team-4" class="collapse" data-parent="#dota2Accordion">  
                                        <p>Team Thunder relies on precise skill execution and map awareness!</p>
                                    </div>
                                </div>

                                <!-- Team 5 -->
                                <div class="list-group-item">
                                    <button class="team-button btn btn-primary" data-toggle="collapse" data-target="#dota2-team-5" aria-expanded="false" aria-controls="dota2-team-5">
                                        Team Phoenix - 670 Points
                                    </button>
                                    <div id="dota2-team-5" class="collapse" data-parent="#dota2Accordion">  
                                        <p>Team Phoenix excels at team fights and finding crucial pick-offs!</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>      
    </div>
</div>

<!-- Upcoming Tournaments Section with Bootstrap Cards -- All descriptions are generated by AI and is fake, this is just sample information!! -->

<section class="upcoming-tournaments" id="upcoming-tournaments">
    <h2>Tournaments</h2>
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Upcoming Matches</h5>
            <div class="accordion" id="tournamentAccordion">
            <ul>
                <li>
                    <a class="d-block" data-toggle="collapse" href="#tournament1" role="button" aria-expanded="false" aria-controls="tournament1">
                        <strong>Battle Royale Invitational - Fortnite</strong> - Date: May 25, 2025
                    </a>
                    <div class="collapse" id="tournament1" data-parent="#tournamentAccordion">
                        <div class="card card-body mt-2">
                            <p><strong>Description:</strong> The Battle Royale Invitational is an online-only event bringing together top competitive fortnite players from around the world. Contestants battle it out in a last-duo-standing format, where only the best duo survives to claim the grand prize.</p>
                            <p><strong>Location:</strong> Online</p>
                            <p><strong>Format:</strong> Last man standing with only duo teams allowed.</p>
                            <p><strong>Prize Pool:</strong> $100,000</p>
                            <p><strong>Player Requirements:</strong> Players must be ranked in the top 100 of the global leaderboard to qualify.</p>
                            <p><strong>Registration Deadline:</strong> May 7, 2025</p>
                        </div>
                    </div>
                </li>
                <li>
                    <a class="d-block" data-toggle="collapse" href="#tournament2" role="button" aria-expanded="false" aria-controls="tournament2">
                        <strong>Champion's League - Valorant</strong> - Date: June 18, 2025
                    </a>
                    <div class="collapse" id="tournament2" data-parent="#tournamentAccordion">
                        <div class="card card-body mt-2">
                            <p><strong>Description:</strong> The Champion's League is an annual tournament featuring the world’s best valorant players. This tournament is played in a series of group stages followed by knockout rounds.</p>
                            <p><strong>Location:</strong> Perth Stadium </p>
                            <p><strong>Format:</strong> Group stages followed by single-elimination knockout rounds.</p>
                            <p><strong>Prize Pool:</strong> $500,000</p>
                            <p><strong>Player Requirements:</strong> Players must be part of an accredited esports team or organization.</p>
                            <p><strong>Registration Deadline:</strong> June 1, 2025</p>
                        </div>
                    </div>
                </li>
                <li>
                    <a class="d-block" data-toggle="collapse" href="#tournament3" role="button" aria-expanded="false" aria-controls="tournament3">
                        <strong>Esports Championship - League of Legends</strong> - Date: July 28, 2025
                    </a>
                    <div class="collapse" id="tournament3" data-parent="#tournamentAccordion">
                        <div class="card card-body mt-2">
                            <p><strong>Description:</strong> The Esports Championship brings together elite players, competing for the title of best overall league of legends esports team. The tournament will span over several weeks.</p>
                            <p><strong>Location:</strong> Las Vegas</p>
                            <p><strong>Format:</strong> Round-robin group stages, followed by best-of-three and best-of-five rounds in the knockout stages.</p>
                            <p><strong>Prize Pool:</strong> $750,000</p>
                            <p><strong>Player Requirements:</strong> Open to teams with at least five members from any esports discipline.</p>
                            <p><strong>Registration Deadline:</strong> July 15, 2025</p>
                        </div>
                    </div>
                </li>
                <li>
                    <a class="d-block" data-toggle="collapse" href="#tournament4" role="button" aria-expanded="false" aria-controls="tournament4">
                        <strong>World Championship - Dota 2, Dead By Daylight, Rocket League</strong> - Date: September 29, 2025
                    </a>
                    <div class="collapse" id="tournament4" data-parent="#tournamentAccordion">
                        <div class="card card-body mt-2">
                            <p><strong>Description:</strong> The World Championship is the pinnacle of competitive gaming, featuring the top players across multiple genres. This tournament is considered the ultimate test for esports athletes, where the best of the best compete for international glory.</p>
                            <p><strong>Location:</strong> Tokyo </p>
                            <p><strong>Format:</strong> Best-of-five series for the final stage, with earlier rounds consisting of single-elimination matches.</p>
                            <p><strong>Prize Pool:</strong> $2,000,000</p>
                            <p><strong>Player Requirements:</strong> Only the top 10 ranked teams in each game will qualify.</p>
                            <p><strong>Registration Deadline:</strong> September 10, 2025</p>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</section>

<!-- Live Stream Section -- All descriptions are generated by AI and is fake, this is just sample information!! However, twitch streams and links were thoroughly researched! -->

<div id="live-streams" class="container mt-5 live-streams-section">
    <h2>Top Streams - Popular Games</h2>
    <div class="row">
        <!-- League of Legends Stream - Caedrel -->
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Caedrel - League of Legends</h5>
                    <p class="card-text">Watch Caedrel live as he plays League of Legends with incredible skill and strategy.</p>
                    
                    <!-- Embed Twitch Stream for Caedrel (League of Legends) -->
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe src="https://player.twitch.tv/?channel=caedrel&parent=localhost" 
                                height="315" width="560" frameborder="0" scrolling="no" allowfullscreen="true" loading="lazy"></iframe>
                    </div>

                    <a href="https://www.twitch.tv/caedrel" class="btn btn-primary mt-3" target="_blank">Watch on Twitch</a>
                </div>
            </div>
        </div>

        <!-- Valorant Stream - Grimm -->
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Grimm - Valorant</h5>
                    <p class="card-text">Watch Grimm dominate the battlefield in Valorant with incredible shooting accuracy and game sense.</p>
                    
                    <!-- Embed Twitch Stream for Grimm (Valorant) -->
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe src="https://player.twitch.tv/?channel=grimm&parent=localhost" 
                                height="315" width="560" frameborder="0" scrolling="no" allowfullscreen="true" loading="lazy"></iframe>
                    </div>

                    <a href="https://www.twitch.tv/grimm" class="btn btn-primary mt-3" target="_blank">Watch on Twitch</a>
                </div>
            </div>
        </div>

        <!-- Rocket League Stream - Fairy Peak -->
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Fairy Peak - Rocket League</h5>
                    <p class="card-text">Join Fairy Peak as he shows off his Rocket League skills, playing exciting matches and tournaments.</p>
                    
                    <!-- Embed Twitch Stream for Fairy Peak (Rocket League) -->
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe src="https://player.twitch.tv/?channel=fairypeak&parent=localhost" 
                                height="315" width="560" frameborder="0" scrolling="no" allowfullscreen="true" loading="lazy"></iframe>
                    </div>

                    <a href="https://www.twitch.tv/fairypeak" class="btn btn-primary mt-3" target="_blank">Watch on Twitch</a>
                </div>
            </div>
        </div>
    </div>
    
    <div class="row mt-4">
        <!-- Fortnite Stream - Nick Eh 30 -->
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Nick Eh 30 - Fortnite</h5>
                    <p class="card-text">Watch Nick Eh 30 battle it out in Fortnite with high-octane action and legendary building skills.</p>
                    
                    <!-- Embed Twitch Stream for Nick Eh 30 (Fortnite) -->
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe src="https://player.twitch.tv/?channel=nickeh30&parent=localhost" 
                                height="315" width="560" frameborder="0" scrolling="no" allowfullscreen="true" loading="lazy"></iframe>
                    </div>

                    <a href="https://www.twitch.tv/nickeh30" class="btn btn-primary mt-3" target="_blank">Watch on Twitch</a>
                </div>
            </div>
        </div>

        <!-- Dead by Daylight Stream - Slate -->
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Slate- Dead by Daylight</h5>
                    <p class="card-text">Watch Slate survive in Dead by Daylight with a mix of horror and thrilling escapes.</p>
                    
                    <!-- Embed Twitch Stream for Slate (Dead by Daylight) -->
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe src="https://player.twitch.tv/?channel=slate&parent=localhost" 
                                height="315" width="560" frameborder="0" scrolling="no" allowfullscreen="true" loading="lazy"></iframe>
                    </div>

                    <a href="https://www.twitch.tv/slate" class="btn btn-primary mt-3" target="_blank">Watch on Twitch</a>
                </div>
            </div>
        </div>

        <!-- Dota 2 Stream - blitzspanks-->
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Blitzspanks - Dota 2</h5>
                    <p class="card-text">Watch Blitzspanks’ Dota 2 team in action as they compete in top-tier tournaments and epic matches.</p>
                    
                    <!-- Embed Twitch Stream for Blitzspanks (Dota 2) -->
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe src="https://player.twitch.tv/?channel=blitzspanks&parent=localhost" 
                                height="315" width="560" frameborder="0" scrolling="no" allowfullscreen="true" loading="lazy"></iframe>
                    </div>

                    <a href="https://www.twitch.tv/blitzspanks" class="btn btn-primary mt-3" target="_blank">Watch on Twitch</a>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Social Media Section -->

<section class="social-media" id="follow-us">
    <h2>Follow Us</h2>
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Connect with us on social media</h5>
            <ul>
                <li><a href="https://facebook.com/esportsarena" target="_blank" class="social-icon facebook">Facebook</a></li>
                <li><a href="https://twitter.com/esportsarena" target="_blank" class="social-icon twitter">Twitter</a></li>
                <li><a href="https://instagram.com/esportsarena" target="_blank" class="social-icon instagram">Instagram</a></li>
                <li><a href="https://youtube.com/esportsarena" target="_blank" class="social-icon youtube">YouTube</a></li>
                <li><a href="https://discord.gg/esportsarena" target="_blank" class="social-icon discord">Discord</a></li>
            </ul>
        </div>
    </div>
</section>

<!-- Posts Section -->
 
<section id="latest-posts" class="posts-section">
    <h2>Latest Posts</h2>
    <?php if (have_posts()) : ?>
        <?php if (is_search()) : ?>
            <section class="search-results">
                <h2>Search Results for: <?php echo get_search_query(); ?></h2>
            </section>
        <?php endif; ?>

        <div class="posts">
            <?php while (have_posts()) : the_post(); ?>
                <div class="post-item">
                    <h3><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3>
                    <p><?php the_excerpt(); ?></p>
                </div>
            <?php endwhile; ?>
        </div>
    <?php else : ?>
        <section class="no-results">
            <p>No results found. Please try a different search.</p>
        </section>
    <?php endif; ?>
</section>

<!-- Testimonials Section - Obviously these testimonials are fake. The testimonial descriptions are generated by AI!-->
<section id="testimonials" class="testimonials-section">
    <h2>What Our Gamers Say</h2>
    
    <!-- Bootstrap 4 Carousel -->
    <div id="testimonialsCarousel" class="carousel slide" data-ride="carousel" data-interval="3000">
        <div class="carousel-inner">
            <!-- Testimonial Item 1 -->
            <div class="carousel-item active">
                <div class="testimonial-item">
                    <p>"Esports Arena has the best events, super fun and organized! Can't wait for the next tournament!"</p>
                    <div class="stars">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star-half-alt"></i>
                    </div>
                    <h4>- John Doe, Gamer</h4>
                </div>
            </div>
            <!-- Testimonial Item 2 -->
            <div class="carousel-item">
                <div class="testimonial-item">
                    <p>"A fantastic community! I’ve met so many awesome people here, and the tournaments are always intense!"</p>
                    <div class="stars">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star-half-alt"></i>
                    </div>
                    <h4>- Jane Smith, Professional Player</h4>
                </div>
            </div>
            <!-- Testimonial Item 3 -->
            <div class="carousel-item">
                <div class="testimonial-item">
                    <p>"The most competitive environment for esports fans. Highly recommend joining if you’re serious about gaming!"</p>
                    <div class="stars">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                    </div>
                    <h4>- Alex Turner, Streamer</h4>
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="carousel-control-prev" href="#testimonialsCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#testimonialsCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</section>


<?php get_footer(); ?>